version: '3'

services:

  myapp-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1981msavanss
      - MYSQL_DATABASE=inatel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1981msavanss
    ports:
      - 3306:3306

  myapp-main:
    image: stock-manager 
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_USER=root
      - DATABASE_PASSWORD=1981msavanss
      - DATABASE_NAME=inatel
      - DATABASE_PORT=3306
      
  myapp-sec:
    image: stock-quote-manager 
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8081:8081
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_USER=root
      - DATABASE_PASSWORD=1981msavanss
      - DATABASE_NAME=inatel
      - DATABASE_PORT=3306